config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :problems
  resources :solutions
  resources :tags

  post 'problems/like/:id' => 'problems#like', as: :problems_like
  post 'problems/dislike/:id' => 'problems#dislike', as: :problems_dislike
  post 'solutions/like/:id' => 'solutions#like', as: :solutions_like
  post 'solutions/dislike/:id' => 'solutions#dislike', as: :solutions_dislike

  get 'ajax/problems/search' => 'problems#search', as: :problems_search
  get 'ajax/tags/search' => 'tags#search', as: :tags_search
  get 'ajax/tags/names' => 'tags#names', as: :tags_names
  get 'ajax/get_session_user_id' => 'users#ajax_get_session_user_id'

  get 'auth/:provider/callback' => 'login#success'
  get 'auth/failure' => 'login#failure'

  get 'login' => 'users#login', as: :user_login
  get 'login_done' => 'users#login_done', as: :login_complete
  get 'logout' => 'users#logout', as: :user_logout
  get 'users/setting' => 'users#setting', as: :user_setting
  post 'users/save_changes' => 'users#save_changes'
  get 'users/:id' => 'users#show', as: :user

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :user_badges
  has_many :users ,through: :user_badges
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  has_many :solutions
  has_many :problem_tags
  has_many :tags, through: :problem_tags

  require 'uri'

  def link?
    uri = URI.parse(description)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end

  def self.search(search, page = 1)
    where("unique_name LIKE :search OR title LIKE :search", search: "%#{search}%")
      .offset((page-1)*5)
      .limit(5)
  end

  def self.search_all(search)
    where("unique_name LIKE :search OR title LIKE :search", search: "%#{search}%")
  end

end

app/models/problem_tag.rb
class ProblemTag < ActiveRecord::Base
  belongs_to :problem
  belongs_to :tag
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :problem
  belongs_to :user
  has_many :solution_tags
  has_many :tags, through: :solution_tags
end

app/models/solution_tag.rb
class SolutionTag < ActiveRecord::Base
  belongs_to :solution
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :problem_tags
  has_many :problem, through: :problem_tags
  has_many :solution_tags
  has_many :solution, through: :solution_tags

  def self.search(keyword, category)
    if (category.nil? || category.empty?)
      where "name LIKE :keyword", keyword: "%#{keyword}%"
    else
      where "category = :category AND name LIKE :keyword", keyword: "%#{keyword}%", category: category
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :problems
  has_many :solutions
  has_many :user_badges
  has_many :badges ,through: :user_badges
  has_many :user_infos

  def get key
    info = UserInfo.find_by user_id: id, category: key
    return info.value unless info.nil?
  end

  def set key, value
    info = UserInfo.find_or_create_by user_id: id, category: key
    info.value = value
    info.save!
  end

  def get key, defval
    info = UserInfo.find_by user_id: id, category: key
    if info == nil
      set key defval
    end
    return UserInfo.find_by user_id: id, category: key
  end
  
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :user
end

app/controllers/badge_controller.rb
class BadgeController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def success
    flash['login_status'] = {
      provider: request.env['omniauth.auth'][:provider],
      uid: request.env['omniauth.auth'][:uid],
      email: request.env['omniauth.auth'].fetch(:info, {}).fetch(:email, nil)
    }
    flash['login_status'][:email] ||= request.env['omniauth.auth']
      .fetch(:extra, {})
      .fetch(:raw_info, {})
      .fetch(:email, nil)
    redirect_to login_complete_path
  end
  def failure
    flash['login_status'] = nil
    redirect_to login_complete_path
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :get_problem_fields, :only => [:create, :update]
  before_filter :get_problem, :only => [:show, :update, :edit, :like, :dislike]
  before_filter :acl_user!, :only => [:new, :create]

  def index
    # if params.has_key?(:search)
    #  @problems = Problem.search_all(params.fetch(:search))
    # else
    #  @problems = Problem.all
    # end
    @search_key = params.fetch(:search, '')
    @problems = []
  end

  def new
    @problem = Problem.new
  end
  
  def create
    @problem_fields['user_id'] = session['user_id']
    Problem.create(@problem_fields)
    redirect_to problems_path
  end

  def show
  end

  def edit
    render :new
  end

  def destroy
  end

  def update
    @problem.update!(@problem_fields)
    flash[:success] = "Problem updated!"
    redirect_to problems_path
  end

  def search
    @problems = Problem.search(params.require(:q), params.fetch(:page, 1))
    @problems = @problems.all
    @result = []
    for prob in @problems do
      @result << [prob, prob.solutions.all]
    end
    render json: @result
  end

  def like
    @problem.rating += 1
    @problem.save!
    render json: { count: @problem.rating, id: @problem.id }
  end

  def dislike
    @problem.rating -= 1
    @problem.save!
    render json: { count: @problem.rating, id: @problem.id }
  end


  def get_problem_fields
    @problem_fields = params.require(:problem).permit(:title, :unique_name, :description, :user_id)
  end

  def get_problem
    @problem = Problem.find(params.fetch(:id))
    # TODO redirect if no match
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :get_tag, :only => [:create, :update]

  def index
    @tags = Tag.all
  end

  def new
    @tag = @tag.new
  end

  def create
    Tag.create @tag
    redirect_to tags_path
  end

  def edit
  end

  def destroy
  end

  def update
  end

  def search
    @result = Tag.search(params[:q], params[:category])
    render json: @result.all
  end

  def names
    render json: Tag.select(:name).map {|x| x.name}
  end

  def get_tag
    @tag = params.require(:tag).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :acl_admin!, only: [:show]
  before_filter :acl_user!, only: [:setting, :save_changes]
  before_filter :get_user, only: [:show]

  def login
  end

  def show
  end

  def login_done
    unless flash['login_status']
      flash[:danger] = I18n.t('login.login_error')
      return redirect_to root_path
    end
    email = flash['login_status']['email']
    user = User.find_by_email(email)
    unless user
      user = User.create({
        email: email,
        group: 'user',
        rating: 0
      })
    end

    unless user
      flash[:danger] = I18n.t('login.login_error')
    end

    if user
      session[:user_id] = user.id
      session[:group] = user.group
      flash[:success] = I18n.t('login.success') + ' ' + email
    end 

    redirect_to root_path
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def setting
  end

  def save_changes
    @user.name = params['new_name']
    @user.save!
    redirect_to user_setting_path
  end

  def get_user
    @user = User.find(session[:user_id])
  end

  def ajax_get_session_user_id
    render text: session.fetch(:user_id, '-1')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login?
    session.has_key?(:user_id)
  end

  def current_user
    return nil if !login?
    return User.find(session[:user_id])
  end

  def no_permission
    flash[:danger] = I18n.t('You have no permission.')
    redirect_to '/'
  end
  
  COLORS = ['yellow', 'green', 'blue', 'orange', 'purple', 'red', 'teal']

  def tag_color(name)
    require 'zlib'
    COLORS[Zlib.crc32(name) % 7]
  end
end

app/helpers/badge_helper.rb
module BadgeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/problems/index.slim
h1 Problems



a href="#{new_problem_path}"
  .ui.button
    | New Problem

a href="#{new_solution_path}"
  .ui.button
    | New Solution

#search-result-segment
  - for prob in @problems do
    .ui.segment
      a.ui.black.ribbon.label href="#{prob.link? ? prob.description : problem_path(prob)}"
        | Problem link
      .ui.grid
        .four.wide.column
          h2.ui.header 
            | #{prob.title}
            .sub.header #{prob.unique_name}
        .eight.wide.column
          - prob.tags.each do |tag|
            .ui.horizontal.label.ptag class="#{tag_color(tag.name)}" #{tag.name}
        .four.wide.column
          .ui.small.buttons
            .ui.button New Solution
            .or
            .ui.button Edit Problem
      .ui.six.doubling.cards
        - for sol in prob.solutions do
          .card
            .content
              | #{sol.rating}
              a.right.floated
                i.thumbs.outline.down.icon
              a.right.floated
                i.thumbs.outline.up.icon
            .ui.two.bottom.attached.buttons
              a.ui.primary.button href="#{sol.content}"
                | link
              a.ui.button href="#{solution_path(sol)}"
                | more

css:
  .problem:nth-child(even) {
    background-color: #EEE;
  }
  .ptitle {
    margin-right: 1em;
  }
  .ptag.ui.horizontal.label {
    padding: 0.1em 0.5em;
  }
  .sol-link {
    padding: 0 10px;
  }
  .sc-z-high {
    z-index: 100;
  }
  a.sc-hover-red:hover {
    color: #D95C5C !important;
  }
  a.sc-hover-green:hover {
    color: #5BBD72 !important;
  }

javascript:
  $(function() {
    Problem.init("#{@search_key}");
  });

app/views/problems/new.slim
== form_for @problem do |f|
  p
    == f.label :problem, :title
    == f.text_field :title
  p
    == f.label :problem, :unique_name
    == f.text_field :unique_name
  p
    == f.label :problem, :description
    == f.text_area :description
  == f.submit

app/views/problems/show.slim
h1 #{@problem.title} (#{@problem.unique_name})
h4 Uploaded by #{@problem.user.name}, #{time_ago_in_words(@problem.created_at)} ago
p =@problem.description
p
  =link_to "+1", problems_like_path, class: 'vote', method: :post, remote: true
  =="/"
  =link_to "-1", problems_dislike_path, class: 'vote', method: :post, remote: true
=="Rating: "
span id="vote"
  =@problem.rating
h2 Discussion

javascript:
  $(document).on('ajax:success', 'a.vote', function (status,data,xhr) {
    $("#vote").text(data.count);
    console.log(data.count);
    return;
  });

css:
  a.vote:focus {
    outline: 0
  }

app/views/users/login.slim
p
  a href="#{Rails.application.config.login_google_path}"
    | Login Through Google+

app/views/users/setting.slim
h1 =@user.name
= form_tag "/users/save_changes"
  p
    = label_tag 'name', 'Display name: '
    = text_field_tag 'new_name', @user.name
  p = submit_tag

app/views/users/show.slim
h1 =@user.name
h2 Uploaded Problems
ul
  - @user.problems.each do |prob|
    li = link_to prob.unique_name, problem_path(prob)
h2 Uploaded Solutions
ul
  - @user.solutions.each do |sol|
    li = link_to sol.problem.unique_name, solution_path(sol)