config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :problems
  resources :solutions
  resources :tags

  post 'problems/like/:id' => 'problems#like', as: :problems_like
  post 'problems/dislike/:id' => 'problems#dislike', as: :problems_dislike
  post 'solutions/like/:id' => 'solutions#like', as: :solutions_like
  post 'solutions/dislike/:id' => 'solutions#dislike', as: :solutions_dislike

  get 'ajax/problems/search' => 'problems#search', as: :problems_search
  get 'ajax/tags/search' => 'tags#search', as: :tags_search
  get 'ajax/tags/names' => 'tags#names', as: :tags_names
  get 'ajax/get_session_user_id' => 'users#ajax_get_session_user_id'

  get 'auth/:provider/callback' => 'login#success'
  get 'auth/failure' => 'login#failure'

  get 'login' => 'users#login', as: :user_login
  get 'login_done' => 'users#login_done', as: :login_complete
  get 'logout' => 'users#logout', as: :user_logout
  get 'users/setting' => 'users#setting', as: :user_setting
  post 'users/save_changes' => 'users#save_changes'
  get 'users/:id' => 'users#show', as: :user

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :user_badges
  has_many :users ,through: :user_badges
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  has_many :solutions
  has_many :problem_tags
  has_many :tags, through: :problem_tags

  require 'uri'

  def link?
    uri = URI.parse(description)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end

  def self.search(search, page = 1)
    where("unique_name LIKE :search OR title LIKE :search", search: "%#{search}%")
      .offset((page-1)*5)
      .limit(5)
  end

  def self.search_all(search)
    where("unique_name LIKE :search OR title LIKE :search", search: "%#{search}%")
  end

end

app/models/problem_tag.rb
class ProblemTag < ActiveRecord::Base
  belongs_to :problem
  belongs_to :tag
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :problem
  belongs_to :user
  has_many :solution_tags
  has_many :tags, through: :solution_tags
end

app/models/solution_tag.rb
class SolutionTag < ActiveRecord::Base
  belongs_to :solution
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :problem_tags
  has_many :problem, through: :problem_tags
  has_many :solution_tags
  has_many :solution, through: :solution_tags

  def self.search(keyword, category)
    if (category.nil? || category.empty?)
      where "name LIKE :keyword", keyword: "%#{keyword}%"
    else
      where "category = :category AND name LIKE :keyword", keyword: "%#{keyword}%", category: category
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :problems
  has_many :solutions
  has_many :user_badges
  has_many :badges ,through: :user_badges
  has_many :user_infos

  def get key
    info = UserInfo.find_by user_id: id, category: key
    return info.value unless info.nil?
  end

  def set key, value
    info = UserInfo.find_or_create_by user_id: id, category: key
    info.value = value
    info.save!
  end

  def get key, defval
    info = UserInfo.find_by user_id: id, category: key
    if info == nil
      set key defval
    end
    return UserInfo.find_by user_id: id, category: key
  end
  
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :user
end

app/controllers/badge_controller.rb
class BadgeController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def success
    flash['login_status'] = {
      provider: request.env['omniauth.auth'][:provider],
      uid: request.env['omniauth.auth'][:uid],
      email: request.env['omniauth.auth'].fetch(:info, {}).fetch(:email, nil)
    }
    flash['login_status'][:email] ||= request.env['omniauth.auth']
      .fetch(:extra, {})
      .fetch(:raw_info, {})
      .fetch(:email, nil)
    redirect_to login_complete_path
  end
  def failure
    flash['login_status'] = nil
    redirect_to login_complete_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :get_tag, :only => [:create, :update]

  def index
    @tags = Tag.all
  end

  def new
    @tag = @tag.new
  end

  def create
    Tag.create @tag
    redirect_to tags_path
  end

  def edit
  end

  def destroy
  end

  def update
  end

  def search
    @result = Tag.search(params[:q], params[:category])
    render json: @result.all
  end

  def names
    render json: Tag.select(:name).map {|x| x.name}
  end

  def get_tag
    @tag = params.require(:tag).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login?
    session.has_key?(:user_id)
  end

  def current_user
    return nil if !login?
    return User.find(session[:user_id])
  end

  def no_permission
    flash[:danger] = I18n.t('You have no permission.')
    redirect_to '/'
  end
  
  COLORS = ['yellow', 'green', 'blue', 'orange', 'purple', 'red', 'teal']

  def tag_color(name)
    require 'zlib'
    COLORS[Zlib.crc32(name) % 7]
  end
end

app/helpers/badge_helper.rb
module BadgeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.slim
ui.segment
  .ui.fixed.menu
    .ui.grid
      .two.wide.column
        a.item href="#{root_path}"
          i.home.icon
          | Home
      .ten.wide.column
        == render 'layouts/search'
      .four.wide.column
        - if !login?
          a.item.right href="#{user_login_path}"
            i.sign.in.icon
            | Login
        - else
          a.item.right href="#{user_setting_path}"
            i.setting.icon
            | Setting
          a.item.right href="#{user_logout_path}"
            i.sign.out.icon
            | Logout
        - if login?
          - user = User.find(session[:user_id])
          a.item.right href="#{user_path(user)}"
            i.user.icon
            == user.name

app/views/layouts/_search.html.slim
== form_tag problems_path, :method => 'get', :class => 'ui form' do
  .ui.grid
    .twelve.wide.column
      .ui.fluid.floating.dropdown
        .ui.input
          == text_field_tag :search, params[:search], :placeholder => 'Search problems...', :id => 'srh', :autocomplete => 'off'
        .menu#search-result-box
    .four.wide.column
      == submit_tag 'search', :name => nil, :class => 'ui icon button'
        i.search.icon

app/views/layouts/application.html.slim
== "<!DOCTYPE html>"
html
  head
    title SoluionCollection
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags

  body
    == render 'layouts/header'
    .container
      - flash.each do |key, value|
        .alert class="alert-#{key}" #{value}
      == yield